### ISSUE TITLE
Pre-audit requirements

### ISSUE THREAD

**Issue by benluelo** [unionlabs/union#1090]
This is a tracking issue for testing that needs to be done across the repo pre-mainnet. [All of these components need to be tested](https://gist.github.com/cor/fdd3dd0e3ecff31458d3c084686979ea)

## Components:

- [ ] eth light client (@aeryz, @benluelo) - partially resolved with #1149
- [ ] cometbls light client (@aeryz, @benluelo)
  - will likely be tested with either the same mini-framework (yet to be written) as the eth lc, or in a very similar way
- [x] #1097
  - is this fuzzable?
- [x] #1096
- [x] #1114
- [x] cosmos-sdk fork (@PoisonPhang) unionlabs/cosmos-sdk#197
  - [x] epoch staking
 
## Libraries:

- [ ] unionlabs (@benluelo, possibly also @aeryz)
  - [ ] test and fuzz the ser/de and encoding/decodings of all types. see #409
  - [ ] review types, lift all invariants to the type level. see #286
- [x] ethereum-verifier (@aeryz): #1149
- [x] ics23 (@aeryz): #1131

# Documentation

All components should have a readme describing their functionality and where they fit in the overall stack.

- [ ] eth light client (@aeryz)
- [ ] cometbls wasm light client (@aeryz)
- [ ] cometbls solidity light client (@hussein-aitlahcen)
- [ ] ucs01-relay (@hussein-aitlahcen)
- [x] galois (@hussein-aitlahcen)
- [x] cosmos-sdk fork (@PoisonPhang)
  - [x] epoch staking (@PoisonPhang)
- [ ] ibc-go for light client changes (@aeryz)
- [ ] union chain
  - [ ] wasm host functions and ibc client override (@aeryz)
  - [x] #1194

- [ ] unionlabs (@benluelo)
- [ ] ethereum-verifier (@aeryz)
- [ ] ics23 (@aeryz)

## Fuzzing

Ideally, fuzzing is a "last resort" - guided fuzzing is hard, and kani should be preferred wherever possible (NOTE: packaging kani in nix turned out to be practically impossible - this will be addressed again down the line). Fuzzing should be used to ensure roundtrip encoding/decoding, etc.

## Coverage

Coverage should be a guide, not a metric. It also takes forever to build and run the rust llvm-code-cov, so it's not worth the time.

## Testing Documentation

I also suggest that we document what we are testing and what are the scenarios. Since all the components are very different from each other, it's good to keep track of which scenarios are we testing. For example for a verification, there might be few scenarios that is needed to be covered for a single function.

# Nice to haves

- https://github.com/unionlabs/union/issues/1043

---

Please leave a comment if I've missed any components, or if anything can be split up into smaller libraries/ subcomponents that can be tested standalone. Feel free to create separate issues for individual components and link them here as well.

Note that voyager, zerg, ucli, hubble, etc are not on this list - since those components hold no trust assumptions, they have very low priority for testing until after we go into audit.
