### ISSUE TITLE
[Tracking] App MVP

### ISSUE THREAD

**Issue by cor** [unionlabs/union#1999]
Ranked in order of priority

- [x] Granular wallet requirements (in progress: @Swepool )
- [x] Redirect to transfer page when no wallet connected
- [x] Better cosmos wallet tx submission progress
- [x] Clickable top hash
- [x] Fix transfer form box size
- [x] disable hidden faucets
- [x] disable sign in wall

## General
- [x] #2129
- [x] #2166
- [x] Add border back to toasts
- [x] #2175
- [x] #2131 (in progress)
- [x] #2140 (pr made)
- [x] #2141 (in progress)

## Home Page
- [x] #2013

## Transfer Page

- [x] #2100
- [x] #2000
- [x] #2174
- [x] #2143
- [x] Propagate contract execution errors to user
- [x] #2169

## Home (dashboard) Page

- [ ] Cool welcome screen for when users have not yet connected their wallets
- [x] Merge ethereum and cosmos balances
- [x] Show user balances in a beautiful format

## Explorer Pages

- [x] #2003
- [x] #2004
- [x] #2011
- [x] #2005
- [x] #2147
- [x] Use new PFM data
- [x] Use master-detail layout rather than sidebar on mobile
- [x] #2280
- [x] #2170
- [x] Simpler tables on mobile

## Transfer Details Explorer

- [x] #2285
- [x] #2287
- [x] Make design mobile friendly

## Faucet Page
- [x] #2002
- [x] #2155
- [x] #2171

## Misc fixes
- [x] #2153
- [x] #2154

## Fun
- [x] CRT effect
- [ ] #2501
- [x] #2212
- [x] #2218

## Shelved
- [ ] #2001
- [x] #2130
- [x] #2144
- [ ] Initiate non-UCS01 transfers
