### ISSUE TITLE
drip improvements

### ISSUE THREAD

**Issue by benluelo** [unionlabs/union#2354]
- [x] https://github.com/unionlabs/union/pull/2353#discussion_r1659423502
- [x] https://github.com/unionlabs/union/pull/2353#discussion_r1659423156
- [ ] strongly typed errors (don't hijack `tx_hash` anymore)
- [ ] return timeout duration in ratelimit error response?
- [ ] use a regular `MsgSend` if there's only one transfer in the queue (slight gas savings)
