### ISSUE TITLE
Open-sourcing

### ISSUE THREAD

**Issue by cor** [unionlabs/union#2725]
- [x] #2726
- [x] #2733
- [x] Header image for README
- [x] Cleanup top-level config files
- [x] #2750
- [ ] #2751
- [ ] Update README for hubble

## will happen after open-sourcing:
- [ ] #2727
- [ ] #2728
- [x] #2460
