### ISSUE TITLE
Add Union IBC changes to Aptos IBC

### ISSUE THREAD

**Issue by aeryz** [unionlabs/union#3116]
# Phase 1: Modifications
- [x] Change IBC client ids to be `u32`.
- [x] Make IBC commitment paths byte prefixed and ethabi encoded. [example](https://github.com/unionlabs/union/pull/3113/files#diff-11558dbfbd07c7fd56fdb33811e560ae3d4389ca6786ad1d99e3e1a2ac6d5274R14)
- [x] Change commitments to be `keccak256(ethabi.encode(elem))`. [example](https://github.com/unionlabs/union/pull/3113/files#diff-11558dbfbd07c7fd56fdb33811e560ae3d4389ca6786ad1d99e3e1a2ac6d5274R14)
- [x] Check out whether there is a change in any of the committed struct. I remember `packet` is changed for example. And change the types accordingly.
    - [x] `ConnectionEnd` commitment
    - [x] `Channel` commitment
    - [x] `Packet` commitment
- [x] Make sure the event types are being changed accordingly.
- [x] Change `channel-id` and `connection-id` to be `u32`.

# Phase 2: Adding new features
- Intent-based bridging:
    - [x] [recvIntentPacket](https://github.com/unionlabs/union/blob/main/evm/contracts/core/04-channel/IBCPacket.sol#L319)
- Batch packets:
    - [x] [batchAcks](https://github.com/unionlabs/union/blob/main/evm/contracts/core/04-channel/IBCPacket.sol#L121)
    - [x] [batchSend](https://github.com/unionlabs/union/blob/main/evm/contracts/core/04-channel/IBCPacket.sol#L96)
    - [x] We also do batch related operations in the regular IBC functions. So make sure to check those out.
