### ISSUE TITLE
Implement misbehaviour types and misbehaviour checks for the light clients

### ISSUE THREAD

**Issue by aeryz** [unionlabs/union#588]
See the [official docs](https://github.com/cosmos/ibc/tree/main/spec/core/ics-002-client-semantics#misbehaviour-predicatehttps://github.com/cosmos/ibc/tree/main/spec/core/ics-002-client-semantics#misbehaviour-predicate).

**Tasks**
- [ ] Implement misbehavior related types
- [ ] Implement on Ethereum light client
- [ ] Implement on Cometbls light client
