### ISSUE TITLE
ICS20 Blogpost Release Checklist

### ISSUE THREAD

**Issue by cor** [unionlabs/union#850]
**Release Checklist**

- [x] Replace the endpoints we use with `rpc.wakey.uuno` and `grpc.wakey.uno`
- [x] Add one more host to the `grpc` load balancer
- [x] Fund the Voyager accounts
- [x] Fund the Zerg accounts
- [x] Read the blogpost once more, review the contents
- [x] Add a paragraph to the blogpost explaining transfer times and noting future improvements
- [x] Zerg it once more with 12 concurrent accounts
- [x] Karel's PR with UNO in MetaMask #835
- [x] Improve the MetaMask popup for the transfer from Sepolia -> Union to have the correct default amount set for the ETH allowance such that the user does not need to edit the amount input in the popup
- [x] Try sending funds back and forth with the blogpost
- [x] Freeze the validator set
- [ ] Improve Zerg timestamps
