### ISSUE TITLE
Public Testnet Tracking Issue

### ISSUE THREAD

**Issue by KaiserKarel** [unionlabs/union#992]
Tracking small tasks necessary for public testnet.

### Keplr

- [ ] hub
- [ ] add UNO token
- [ ] staking integration

### defilama

- [ ] bridge integration
- [ ] protocol info (total raised, etc).

### frontends

- [ ] Transfers page #1014
- [ ] explorer (bridge)
- [ ] dashboard (chain/protocol incl governance)

### rpc

- [ ] rpc.union.build
- [ ] grpc.union.build

### status page

- [ ] status.union.build

### SDKs

- [ ] Solidity 
- [ ] Typescript (viem, cosmjs) #1014
- [ ] Widget (low prio)
