### ISSUE TITLE
Hubble v0

### ISSUE THREAD

**Issue by KaiserKarel** [unionlabs/union#998]
### Schema

- [ ] Add views for all union event types.
- [ ] Add views for all IBC contract event types (evm).
- [ ] Materialized views for full IBC transfers.
- [ ] Remove internal ID system (?).

### Ethereum

- [ ] Add contract parsing.
- [ ] Add direct-from-db indexing (reth).
   https://github.com/paradigmxyz/reth/blob/cb52a4ca3967b9d9f619d15573e1b293350b1e62/crates/storage/provider/src/providers/database/provider.rs#L935 
https://github.com/paradigmxyz/reth/blob/cb52a4ca3967b9d9f619d15573e1b293350b1e62/crates/storage/provider/src/providers/database/provider.rs#L1354
https://github.com/paradigmxyz/reth/blob/cb52a4ca3967b9d9f619d15573e1b293350b1e62/crates/storage/provider/src/providers/database/provider.rs#L1442

### Hasura

- [ ] Add permissions

### Timescale

- [ ] Debug query performance issues on events table.
